language: elixir
elixir:
  - 1.11.3
otp_release:
  - 23.0.4
script:
  - mix deps.get
  - mix compile
services:
  - docker

before_install:
  - docker-compose up -d

after_script:
  - docker-compose down
