language: elixir
elixir:
  - 1.8.2
otp_release:
  - 22.0

before_script:
  - echo "hello"
  - docker-compose up -d
  - sleep 10
  - echo "hello2"

script:
  - echo "hello3"
  - cd  api
  - pwd
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate
  - mix test
  - cd ../app
  - npm install
  - npm run build
  - npm test
services:
  - docker
  
after_script:
  - docker-compose down
